
import BLL.BLLTaiKhoan;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class DoiMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form DoiMatKhau
     */
    String tenDangNhap;
    BLL.BLLTaiKhoan taiKhoanBLL = new BLLTaiKhoan();

    public DoiMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public DoiMatKhau(java.awt.Frame parent, boolean modal, String tenDangNhap) {
        super(parent, modal);
        this.tenDangNhap = tenDangNhap;
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldMKCu = new javax.swing.JPasswordField();
        jPasswordFieldMKMoi = new javax.swing.JPasswordField();
        jPasswordFieldXacNhanMK = new javax.swing.JPasswordField();
        jButtonDongY = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jCheckBoxHienThiMatKhau = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 292));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mật khẩu cũ:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật khẩu mới:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Xác nhận mật khẩu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPasswordFieldMKCu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordFieldMKCu.setToolTipText("");
        jPasswordFieldMKCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldMKCuActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldMKCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 176, -1));

        jPasswordFieldMKMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordFieldMKMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldMKMoiActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldMKMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 176, -1));

        jPasswordFieldXacNhanMK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordFieldXacNhanMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldXacNhanMKActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldXacNhanMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 176, -1));

        jButtonDongY.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDongY.setText("Đồng ý");
        jButtonDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDongYActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jButtonHuy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jCheckBoxHienThiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHienThiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBoxHienThiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxHienThiMatKhau.setText("Hiển thị mật khẩu");
        jCheckBoxHienThiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxHienThiMatKhauMouseClicked(evt);
            }
        });
        jCheckBoxHienThiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHienThiMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxHienThiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDongYActionPerformed
        try {
            // TODO add your handling code here:
            ResultSet rs = taiKhoanBLL.KiemTraTaiKhoan(tenDangNhap, String.valueOf(jPasswordFieldMKCu.getPassword()));
            if (rs.next()) {
                if (String.valueOf(jPasswordFieldMKMoi.getPassword()).equals(String.valueOf(jPasswordFieldXacNhanMK.getPassword()))) {
                    taiKhoanBLL.updateMatKhau(tenDangNhap, String.valueOf(jPasswordFieldMKMoi.getPassword()));
                    JOptionPane.showMessageDialog(jButtonDongY, "Đổi mật khẩu thành công", "Thông báo", HEIGHT);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(jButtonDongY, "Xác nhận mật khẩu không chính xác", "Lỗi", HEIGHT);
                }
            } else {
                JOptionPane.showMessageDialog(jButtonDongY, "Sai mật khẩu", "Lỗi", HEIGHT);
            }
        } catch (Exception ex) {
            Logger.getLogger(DoiMatKhau.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDongYActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jCheckBoxHienThiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxHienThiMatKhauMouseClicked
        // TODO add your handling code here:
        if (jCheckBoxHienThiMatKhau.isSelected()) {
            jPasswordFieldMKCu.setEchoChar((char) 0);
            jPasswordFieldMKMoi.setEchoChar((char) 0);
            jPasswordFieldXacNhanMK.setEchoChar((char) 0);
        } else {
            jPasswordFieldMKCu.setEchoChar('*');
            jPasswordFieldMKMoi.setEchoChar('*');
            jPasswordFieldXacNhanMK.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxHienThiMatKhauMouseClicked

    private void jCheckBoxHienThiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHienThiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHienThiMatKhauActionPerformed

    private void jPasswordFieldMKCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldMKCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldMKCuActionPerformed

    private void jPasswordFieldMKMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldMKMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldMKMoiActionPerformed

    private void jPasswordFieldXacNhanMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldXacNhanMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldXacNhanMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoiMatKhau dialog = new DoiMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDongY;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JCheckBox jCheckBoxHienThiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldMKCu;
    private javax.swing.JPasswordField jPasswordFieldMKMoi;
    private javax.swing.JPasswordField jPasswordFieldXacNhanMK;
    // End of variables declaration//GEN-END:variables
}
