
import BLL.BLLTaiKhoan;
import DTO.DTOTaiKhoan;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class JFrameTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DTO.DTOTaiKhoan taiKhoan = new DTOTaiKhoan();
    private BLL.BLLTaiKhoan taiKhoanBLL = new BLLTaiKhoan();

    public JFrameTrangChu(String tenDangNhap) {
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        taiKhoan.setTenDangNhap(tenDangNhap);
        TrangChu.setBackground(new Color(85, 65, 118));
//        jTabbedPaneGiaoDien.setSelectedIndex(1);
        jPanel1.revalidate();
        try {
            LoadData();
        } catch (Exception ex) {
            Logger.getLogger(JFrameTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadData() throws Exception {
        ResultSet rs = taiKhoanBLL.ShowThongTinTK(taiKhoan.getTenDangNhap());
        System.out.println(taiKhoan.getTenDangNhap());
        if (rs.next()) {
            taiKhoan.setLoaiTK(Integer.parseInt(rs.getString("loaiTaiKhoan")));
            taiKhoan.setTenNguoiDung(rs.getString("TenNguoiDung"));
            taiKhoan.setMatKhau(rs.getString("MatKhau"));
            jLabelTenNguoiDung.setText(taiKhoan.getTenNguoiDung());
            if(taiKhoan.getLoaiTK()==0){
                ThongKe.setVisible(false);
                jLabelThongKe.setVisible(false);
                QuanLyTaiKhoan.setVisible(false);
                jLabelQuanLyTaiKhoan.setVisible(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        DoiMatKhau = new javax.swing.JMenuItem();
        jMenuItemDangXuat = new javax.swing.JMenuItem();
        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        TrangChu = new javax.swing.JPanel();
        jLabelTextTrangChu = new javax.swing.JLabel();
        jLabelIconTrangChu = new javax.swing.JLabel();
        QuanLyGiaoTrinh = new javax.swing.JPanel();
        jLabelTextQLGiaoTrinh = new javax.swing.JLabel();
        jLabelIconGiaoTrinh = new javax.swing.JLabel();
        QuanLyDanhMuc = new javax.swing.JPanel();
        jLabelTextQLDanhMuc = new javax.swing.JLabel();
        jLabelIconQLDanhMuc = new javax.swing.JLabel();
        QuanLyMuonTra = new javax.swing.JPanel();
        jLabelTextQLMuonTra = new javax.swing.JLabel();
        jLabelIconQLMuonTra = new javax.swing.JLabel();
        QuanLyThanhVien = new javax.swing.JPanel();
        jLabelTextQLThanhVien = new javax.swing.JLabel();
        jLabelIconQLThanhVien = new javax.swing.JLabel();
        QuanLyMuaBan = new javax.swing.JPanel();
        jLabelTextQLMuaBan = new javax.swing.JLabel();
        jLabelIconQLMuaBan = new javax.swing.JLabel();
        NhaXuatBan = new javax.swing.JPanel();
        jLabelTextQLTaiKhoan1 = new javax.swing.JLabel();
        jLabelIconQLTaiKhoan1 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabelTextThongKe = new javax.swing.JLabel();
        jLabelIconThongKe = new javax.swing.JLabel();
        QuanLyTaiKhoan = new javax.swing.JPanel();
        jLabelTextQLTaiKhoan = new javax.swing.JLabel();
        jLabelIconQLTaiKhoan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JPanel();
        jLabelXinChao = new javax.swing.JLabel();
        jLabelTenNguoiDung = new javax.swing.JLabel();
        jLabelIconDropdown = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelQuanLyGiaoTrinh = new javax.swing.JLabel();
        jLabelQuanLyDanhMuc = new javax.swing.JLabel();
        jLabelQuanLyMuonTra = new javax.swing.JLabel();
        jLabelQuanLyThanhVien = new javax.swing.JLabel();
        jLabelQuanLyTaiKhoan = new javax.swing.JLabel();
        jLabelThongKe = new javax.swing.JLabel();
        jLabelQuanLyBanHang = new javax.swing.JLabel();
        jLabelQuanLyNhaXB = new javax.swing.JLabel();

        DoiMatKhau.setText("Đổi mật khẩu");
        DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoiMatKhauActionPerformed(evt);
            }
        });
        jPopupMenu1.add(DoiMatKhau);

        jMenuItemDangXuat.setText("Đăng xuất");
        jMenuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDangXuatActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemDangXuat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(85, 65, 118));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(54, 33, 80));

        TrangChu.setBackground(new java.awt.Color(54, 33, 80));
        TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrangChuMousePressed(evt);
            }
        });

        jLabelTextTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextTrangChu.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextTrangChu.setText("Trang chủ");

        jLabelIconTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-home-20.png"))); // NOI18N

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconTrangChu)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextTrangChu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        QuanLyGiaoTrinh.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyGiaoTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyGiaoTrinhMousePressed(evt);
            }
        });

        jLabelTextQLGiaoTrinh.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLGiaoTrinh.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLGiaoTrinh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLGiaoTrinh.setText("Biên soạn giáo trình");

        jLabelIconGiaoTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-book-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyGiaoTrinhLayout = new javax.swing.GroupLayout(QuanLyGiaoTrinh);
        QuanLyGiaoTrinh.setLayout(QuanLyGiaoTrinhLayout);
        QuanLyGiaoTrinhLayout.setHorizontalGroup(
            QuanLyGiaoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyGiaoTrinhLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconGiaoTrinh)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLGiaoTrinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyGiaoTrinhLayout.setVerticalGroup(
            QuanLyGiaoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyGiaoTrinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyGiaoTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconGiaoTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLGiaoTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        QuanLyDanhMuc.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyDanhMucMousePressed(evt);
            }
        });

        jLabelTextQLDanhMuc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLDanhMuc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLDanhMuc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLDanhMuc.setText("Quản lý danh mục");

        jLabelIconQLDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-book-shelf-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyDanhMucLayout = new javax.swing.GroupLayout(QuanLyDanhMuc);
        QuanLyDanhMuc.setLayout(QuanLyDanhMucLayout);
        QuanLyDanhMucLayout.setHorizontalGroup(
            QuanLyDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDanhMucLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLDanhMuc)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLDanhMuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyDanhMucLayout.setVerticalGroup(
            QuanLyDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        QuanLyMuonTra.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyMuonTraMousePressed(evt);
            }
        });

        jLabelTextQLMuonTra.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLMuonTra.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLMuonTra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLMuonTra.setText("Quản lý mượn - trả");

        jLabelIconQLMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-sell-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyMuonTraLayout = new javax.swing.GroupLayout(QuanLyMuonTra);
        QuanLyMuonTra.setLayout(QuanLyMuonTraLayout);
        QuanLyMuonTraLayout.setHorizontalGroup(
            QuanLyMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyMuonTraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLMuonTra)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLMuonTra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyMuonTraLayout.setVerticalGroup(
            QuanLyMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        QuanLyThanhVien.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyThanhVienMousePressed(evt);
            }
        });

        jLabelTextQLThanhVien.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLThanhVien.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLThanhVien.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLThanhVien.setText("Quản lý sinh viên");

        jLabelIconQLThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-student-male-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyThanhVienLayout = new javax.swing.GroupLayout(QuanLyThanhVien);
        QuanLyThanhVien.setLayout(QuanLyThanhVienLayout);
        QuanLyThanhVienLayout.setHorizontalGroup(
            QuanLyThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyThanhVienLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLThanhVien)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLThanhVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyThanhVienLayout.setVerticalGroup(
            QuanLyThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyThanhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        QuanLyMuaBan.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyMuaBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyMuaBanMousePressed(evt);
            }
        });

        jLabelTextQLMuaBan.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLMuaBan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLMuaBan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLMuaBan.setText("Quản lý mua bán");

        jLabelIconQLMuaBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-initiate-money-transfer-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyMuaBanLayout = new javax.swing.GroupLayout(QuanLyMuaBan);
        QuanLyMuaBan.setLayout(QuanLyMuaBanLayout);
        QuanLyMuaBanLayout.setHorizontalGroup(
            QuanLyMuaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyMuaBanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLMuaBan)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLMuaBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyMuaBanLayout.setVerticalGroup(
            QuanLyMuaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyMuaBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuanLyMuaBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLMuaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLMuaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        NhaXuatBan.setBackground(new java.awt.Color(54, 33, 80));
        NhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaXuatBanMousePressed(evt);
            }
        });

        jLabelTextQLTaiKhoan1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLTaiKhoan1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLTaiKhoan1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLTaiKhoan1.setText("Quản lý nhà xuất bản");

        jLabelIconQLTaiKhoan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-company2-20.png"))); // NOI18N

        javax.swing.GroupLayout NhaXuatBanLayout = new javax.swing.GroupLayout(NhaXuatBan);
        NhaXuatBan.setLayout(NhaXuatBanLayout);
        NhaXuatBanLayout.setHorizontalGroup(
            NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaXuatBanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLTaiKhoan1)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLTaiKhoan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NhaXuatBanLayout.setVerticalGroup(
            NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaXuatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLTaiKhoan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLTaiKhoan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThongKe.setBackground(new java.awt.Color(54, 33, 80));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabelTextThongKe.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextThongKe.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextThongKe.setText("Thống kê");

        jLabelIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-combo-chart-20.png"))); // NOI18N

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconThongKe)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextThongKe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        QuanLyTaiKhoan.setBackground(new java.awt.Color(54, 33, 80));
        QuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QuanLyTaiKhoanMousePressed(evt);
            }
        });

        jLabelTextQLTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextQLTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTextQLTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextQLTaiKhoan.setText("Quản lý tài khoản");

        jLabelIconQLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-management-20.png"))); // NOI18N

        javax.swing.GroupLayout QuanLyTaiKhoanLayout = new javax.swing.GroupLayout(QuanLyTaiKhoan);
        QuanLyTaiKhoan.setLayout(QuanLyTaiKhoanLayout);
        QuanLyTaiKhoanLayout.setHorizontalGroup(
            QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelIconQLTaiKhoan)
                .addGap(26, 26, 26)
                .addComponent(jLabelTextQLTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QuanLyTaiKhoanLayout.setVerticalGroup(
            QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuanLyTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIconQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTextQLTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo300px.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyGiaoTrinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyDanhMuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyMuaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyGiaoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyMuaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 684));

        TaiKhoan.setBackground(new java.awt.Color(110, 89, 222));
        TaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelXinChao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelXinChao.setText("Xin chào:");
        TaiKhoan.add(jLabelXinChao, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabelTenNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelTenNguoiDung.setText("Tên người dùng");
        TaiKhoan.add(jLabelTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabelIconDropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dropdown-field-20.png"))); // NOI18N
        jLabelIconDropdown.setMaximumSize(new java.awt.Dimension(24, 24));
        jLabelIconDropdown.setMinimumSize(new java.awt.Dimension(24, 24));
        jLabelIconDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelIconDropdownMousePressed(evt);
            }
        });
        TaiKhoan.add(jLabelIconDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        Background.add(TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1220, 60));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelQuanLyGiaoTrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Book.png"))); // NOI18N
        jLabelQuanLyGiaoTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuanLyGiaoTrinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuanLyGiaoTrinhMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyGiaoTrinhMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyGiaoTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, -1, -1));

        jLabelQuanLyDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLdanhmuc.png"))); // NOI18N
        jLabelQuanLyDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuanLyDanhMucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuanLyDanhMucMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyDanhMucMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 0, -1, -1));

        jLabelQuanLyMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLMuonTra.png"))); // NOI18N
        jLabelQuanLyMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuanLyMuonTraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuanLyMuonTraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyMuonTraMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyMuonTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 0, -1, -1));

        jLabelQuanLyThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLThanhVienMuonTra.png"))); // NOI18N
        jLabelQuanLyThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelQuanLyThanhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelQuanLyThanhVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyThanhVienMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyThanhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 0, -1, -1));

        jLabelQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLTaiKhoan.png"))); // NOI18N
        jLabelQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyTaiKhoanMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 255, -1, -1));

        jLabelThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe.png"))); // NOI18N
        jLabelThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelThongKeMousePressed(evt);
            }
        });
        jPanel2.add(jLabelThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 255, -1, -1));

        jLabelQuanLyBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLMuaBanGiaoTrinh.png"))); // NOI18N
        jLabelQuanLyBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyBanHangMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 255, -1, -1));

        jLabelQuanLyNhaXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QLNhaXB.png"))); // NOI18N
        jLabelQuanLyNhaXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelQuanLyNhaXBMousePressed(evt);
            }
        });
        jPanel2.add(jLabelQuanLyNhaXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 255, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 1110, 590));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanLyGiaoTrinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyGiaoTrinhMousePressed
        // TODO add your handling code here:
        QuanLyGiaoTrinh.setBackground(new Color(85, 65, 118));
//        jTabbedPaneGiaoDien.setSelectedIndex(0);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyBienSoanGiaoTrinh());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyGiaoTrinhMousePressed

    private void QuanLyDanhMucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyDanhMucMousePressed
        // TODO add your handling code here:
        QuanLyDanhMuc.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(2);
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyDanhMuc());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyDanhMucMousePressed

    private void QuanLyMuonTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyMuonTraMousePressed
        // TODO add your handling code here:
        QuanLyMuonTra.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(6);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyMuonTra1());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyMuonTraMousePressed

    private void QuanLyThanhVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyThanhVienMousePressed
        // TODO add your handling code here:
        QuanLyThanhVien.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(3);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLySinhVien());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyThanhVienMousePressed

    private void QuanLyMuaBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyMuaBanMousePressed
        // TODO add your handling code here:
        QuanLyMuaBan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(5);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyBanGiaoTrinh());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyMuaBanMousePressed

    private void QuanLyTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanLyTaiKhoanMousePressed
        // TODO add your handling code here:
        QuanLyTaiKhoan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(4);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyTaiKhoan());
        jPanel1.revalidate();
    }//GEN-LAST:event_QuanLyTaiKhoanMousePressed

    private void NhaXuatBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaXuatBanMousePressed
        // TODO add your handling code here:
        NhaXuatBan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(7);
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PaneQuanLylNhaXuatBan());
        jPanel1.revalidate();
    }//GEN-LAST:event_NhaXuatBanMousePressed

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(85, 65, 118));
        jPanel1.removeAll();
        jPanel1.add(new PanelThongKe());
        jPanel1.revalidate();
    }//GEN-LAST:event_ThongKeMousePressed

    private void jLabelQuanLyGiaoTrinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyGiaoTrinhMousePressed
        // TODO add your handling code here:
        QuanLyGiaoTrinh.setBackground(new Color(85, 65, 118));
//        jTabbedPaneGiaoDien.setSelectedIndex(0);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyBienSoanGiaoTrinh());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyGiaoTrinhMousePressed

    private void jLabelQuanLyDanhMucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyDanhMucMousePressed
        // TODO add your handling code here:
        QuanLyDanhMuc.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(2);
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyDanhMuc());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyDanhMucMousePressed

    private void jLabelQuanLyMuonTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyMuonTraMousePressed
        // TODO add your handling code here:
        QuanLyMuonTra.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(6);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyMuonTra1());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyMuonTraMousePressed

    private void jLabelQuanLyThanhVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyThanhVienMousePressed
        // TODO add your handling code here:
        QuanLyThanhVien.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(3);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLySinhVien());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyThanhVienMousePressed

    private void jLabelQuanLyBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyBanHangMousePressed
        // TODO add your handling code here:
        QuanLyMuaBan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(5);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyBanGiaoTrinh());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyBanHangMousePressed

    private void jLabelThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelThongKeMousePressed
        // TODO add your handling code here:
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(85, 65, 118));
        jPanel1.removeAll();
        jPanel1.add(new PanelThongKe());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelThongKeMousePressed

    private void jLabelQuanLyTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyTaiKhoanMousePressed
        // TODO add your handling code here:
        QuanLyTaiKhoan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(4);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PanelQuanLyTaiKhoan());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyTaiKhoanMousePressed

    private void jLabelQuanLyNhaXBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyNhaXBMousePressed
        // TODO add your handling code here:
        NhaXuatBan.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(7);
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        TrangChu.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.add(new PaneQuanLylNhaXuatBan());
        jPanel1.revalidate();
    }//GEN-LAST:event_jLabelQuanLyNhaXBMousePressed

    private void jLabelQuanLyThanhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyThanhVienMouseExited
        // TODO add your handling code here:
        jLabelQuanLyThanhVien.setBorder(new LineBorder(Color.BLACK, 0));
    }//GEN-LAST:event_jLabelQuanLyThanhVienMouseExited

    private void jLabelQuanLyThanhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyThanhVienMouseEntered
        // TODO add your handling code here:
        jLabelQuanLyThanhVien.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_jLabelQuanLyThanhVienMouseEntered

    private void jLabelQuanLyMuonTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyMuonTraMouseExited
        // TODO add your handling code here:
        jLabelQuanLyMuonTra.setBorder(new LineBorder(Color.BLACK, 0));
    }//GEN-LAST:event_jLabelQuanLyMuonTraMouseExited

    private void jLabelQuanLyMuonTraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyMuonTraMouseEntered
        // TODO add your handling code here:
        jLabelQuanLyMuonTra.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_jLabelQuanLyMuonTraMouseEntered

    private void jLabelQuanLyDanhMucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyDanhMucMouseExited
        // TODO add your handling code here:
        jLabelQuanLyDanhMuc.setBorder(new LineBorder(Color.BLACK, 0));
    }//GEN-LAST:event_jLabelQuanLyDanhMucMouseExited

    private void jLabelQuanLyDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyDanhMucMouseEntered
        // TODO add your handling code here:
        jLabelQuanLyDanhMuc.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_jLabelQuanLyDanhMucMouseEntered

    private void jLabelQuanLyGiaoTrinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyGiaoTrinhMouseExited
        // TODO add your handling code here:
        jLabelQuanLyGiaoTrinh.setBorder(new LineBorder(Color.BLACK, 0));
    }//GEN-LAST:event_jLabelQuanLyGiaoTrinhMouseExited

    private void jLabelQuanLyGiaoTrinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuanLyGiaoTrinhMouseEntered
        // TODO add your handling code here:
        jLabelQuanLyGiaoTrinh.setBorder(new LineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_jLabelQuanLyGiaoTrinhMouseEntered

    private void DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau doiMatKhau = new DoiMatKhau(null, true, taiKhoan.getTenDangNhap());
        doiMatKhau.setVisible(true);
    }//GEN-LAST:event_DoiMatKhauActionPerformed

    private void jLabelIconDropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconDropdownMousePressed
        // TODO add your handling code here:
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jLabelIconDropdownMousePressed

    private void jMenuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap dangNhap = new DangNhap();
        dangNhap.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemDangXuatActionPerformed

    private void TrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMousePressed
        // TODO add your handling code here:
        TrangChu.setBackground(new Color(85, 65, 118));
        //jTabbedPaneGiaoDien.setSelectedIndex(1);
        NhaXuatBan.setBackground(new Color(54, 33, 80));
        QuanLyTaiKhoan.setBackground(new Color(54, 33, 80));
        QuanLyMuaBan.setBackground(new Color(54, 33, 80));
        QuanLyThanhVien.setBackground(new Color(54, 33, 80));
        QuanLyMuonTra.setBackground(new Color(54, 33, 80));
        QuanLyDanhMuc.setBackground(new Color(54, 33, 80));
        QuanLyGiaoTrinh.setBackground(new Color(54, 33, 80));
        ThongKe.setBackground(new Color(54, 33, 80));
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        jPanel1.add(jPanel2);

    }//GEN-LAST:event_TrangChuMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JMenuItem DoiMatKhau;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel NhaXuatBan;
    private javax.swing.JPanel QuanLyDanhMuc;
    private javax.swing.JPanel QuanLyGiaoTrinh;
    private javax.swing.JPanel QuanLyMuaBan;
    private javax.swing.JPanel QuanLyMuonTra;
    private javax.swing.JPanel QuanLyTaiKhoan;
    private javax.swing.JPanel QuanLyThanhVien;
    private javax.swing.JPanel TaiKhoan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIconDropdown;
    private javax.swing.JLabel jLabelIconGiaoTrinh;
    private javax.swing.JLabel jLabelIconQLDanhMuc;
    private javax.swing.JLabel jLabelIconQLMuaBan;
    private javax.swing.JLabel jLabelIconQLMuonTra;
    private javax.swing.JLabel jLabelIconQLTaiKhoan;
    private javax.swing.JLabel jLabelIconQLTaiKhoan1;
    private javax.swing.JLabel jLabelIconQLThanhVien;
    private javax.swing.JLabel jLabelIconThongKe;
    private javax.swing.JLabel jLabelIconTrangChu;
    private javax.swing.JLabel jLabelQuanLyBanHang;
    private javax.swing.JLabel jLabelQuanLyDanhMuc;
    private javax.swing.JLabel jLabelQuanLyGiaoTrinh;
    private javax.swing.JLabel jLabelQuanLyMuonTra;
    private javax.swing.JLabel jLabelQuanLyNhaXB;
    private javax.swing.JLabel jLabelQuanLyTaiKhoan;
    private javax.swing.JLabel jLabelQuanLyThanhVien;
    private javax.swing.JLabel jLabelTenNguoiDung;
    private javax.swing.JLabel jLabelTextQLDanhMuc;
    private javax.swing.JLabel jLabelTextQLGiaoTrinh;
    private javax.swing.JLabel jLabelTextQLMuaBan;
    private javax.swing.JLabel jLabelTextQLMuonTra;
    private javax.swing.JLabel jLabelTextQLTaiKhoan;
    private javax.swing.JLabel jLabelTextQLTaiKhoan1;
    private javax.swing.JLabel jLabelTextQLThanhVien;
    private javax.swing.JLabel jLabelTextThongKe;
    private javax.swing.JLabel jLabelTextTrangChu;
    private javax.swing.JLabel jLabelThongKe;
    private javax.swing.JLabel jLabelXinChao;
    private javax.swing.JMenuItem jMenuItemDangXuat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
