
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LongTienSinh
 */
public class PanelQuanLyMuonTra1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyMuonTra1
     */
    public PanelQuanLyMuonTra1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DanhSachMuonTra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DangKiMuonTra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelShow = new javax.swing.JPanel();
        panelDanhSachMuonTra2 = new PanelDanhSachMuonTra();

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));

        DanhSachMuonTra.setBackground(new java.awt.Color(80, 65, 118));
        DanhSachMuonTra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        DanhSachMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DanhSachMuonTraMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Danh sách mượn trả");

        javax.swing.GroupLayout DanhSachMuonTraLayout = new javax.swing.GroupLayout(DanhSachMuonTra);
        DanhSachMuonTra.setLayout(DanhSachMuonTraLayout);
        DanhSachMuonTraLayout.setHorizontalGroup(
            DanhSachMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DanhSachMuonTraLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        DanhSachMuonTraLayout.setVerticalGroup(
            DanhSachMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DangKiMuonTra.setBackground(new java.awt.Color(51, 33, 89));
        DangKiMuonTra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        DangKiMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangKiMuonTraMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Đăng ký mượn trả");

        javax.swing.GroupLayout DangKiMuonTraLayout = new javax.swing.GroupLayout(DangKiMuonTra);
        DangKiMuonTra.setLayout(DangKiMuonTraLayout);
        DangKiMuonTraLayout.setHorizontalGroup(
            DangKiMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangKiMuonTraLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
        );
        DangKiMuonTraLayout.setVerticalGroup(
            DangKiMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangKiMuonTraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanelShow.setLayout(new java.awt.BorderLayout());
        jPanelShow.add(panelDanhSachMuonTra2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DanhSachMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DangKiMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DangKiMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DanhSachMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DangKiMuonTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangKiMuonTraMousePressed
        // TODO add your handling code here:
        DanhSachMuonTra.setBackground(new Color(54, 33, 80));
        DangKiMuonTra.setBackground(new Color(80, 65, 118));
        jPanelShow.removeAll();
        jPanelShow.add(new PanelDangKyMuonTra());
        jPanelShow.revalidate();
    }//GEN-LAST:event_DangKiMuonTraMousePressed

    private void DanhSachMuonTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachMuonTraMousePressed
        // TODO add your handling code here:
        DanhSachMuonTra.setBackground(new Color(80, 65, 118));
        DangKiMuonTra.setBackground(new Color(54, 33, 80));
        jPanelShow.removeAll();
        jPanelShow.add(new PanelDanhSachMuonTra());
        jPanelShow.revalidate();
    }//GEN-LAST:event_DanhSachMuonTraMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangKiMuonTra;
    private javax.swing.JPanel DanhSachMuonTra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelShow;
    private PanelDanhSachMuonTra panelDanhSachMuonTra2;
    // End of variables declaration//GEN-END:variables
}
