
import BLL.BLLQuanLySinhVien;
import DTO.DTOSinhVien;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class PanelQuanLySinhVien extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyThanhVien
     */
    public static ResultSet rs = null;
    public BLL.BLLQuanLySinhVien sinhvienBLL = new BLLQuanLySinhVien();
    public ArrayList<DTO.DTOSinhVien> sinhViens = new ArrayList<DTOSinhVien>();

    public PanelQuanLySinhVien() {
        initComponents();
        LoadData();
        jRadioButtonNam.setSelected(true);
    }

    private void LoadBang() {
        jTableThongTinSV.removeAll();
        String[] tieuDe = {"Mã sinh viên", "Tên sinh viên", "Giới tính", "Địa chỉ", "Email"};
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        int i = 0;
        for (DTOSinhVien a : sinhViens) {
            Vector vt = new Vector();
            vt.add(a.getMaSV());
            vt.add(a.getTenSV());
            if (a.getGioiTinh() == 0)//Nam
            {
                vt.add("Nam");
            } else {
                vt.add("Nữ");
            }
            vt.add(a.getDiaChi());
            vt.add(a.getEmail());
            model.addRow(vt);
            i++;
        }
        jTableThongTinSV.setModel(model);
    }

    private void LoadData() {
        try {
            sinhViens.clear();
            rs = sinhvienBLL.ShowSinhVien();
            while (rs.next()) {
                DTOSinhVien a = new DTOSinhVien();
                a.setMaSV(rs.getString("MaSV"));
                a.setTenSV(rs.getString("TenSV"));
                a.setGioiTinh(Integer.parseInt(rs.getString("GioiTinh")));
                a.setDiaChi(rs.getString("DiaChi"));
                a.setEmail(rs.getString("Email"));
                sinhViens.add(a);
            }
            LoadBang();
        } catch (SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(PanelQuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableThongTinSV = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMaSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTenSV = new javax.swing.JTextField();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTimKiemTheo = new javax.swing.JComboBox<>();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(85, 65, 118));

        jTableThongTinSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableThongTinSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableThongTinSV.setFocusable(false);
        jTableThongTinSV.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableThongTinSV.setRowHeight(25);
        jTableThongTinSV.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTableThongTinSV.setShowVerticalLines(false);
        jTableThongTinSV.getTableHeader().setReorderingAllowed(false);
        jTableThongTinSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableThongTinSVMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableThongTinSV);

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã sinh viên: ");

        jTextFieldMaSV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldMaSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMaSVKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên sinh viên: ");

        jTextFieldTenSV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        buttonGroupGioiTinh.add(jRadioButtonNam);
        jRadioButtonNam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonNam.setText("Nam");

        buttonGroupGioiTinh.add(jRadioButtonNu);
        jRadioButtonNu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonNu.setText("Nữ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giới tính: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa chỉ: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email: ");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jTextFieldDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jTextFieldMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jRadioButtonNam)
                                .addGap(68, 68, 68)
                                .addComponent(jRadioButtonNu))
                            .addComponent(jTextFieldTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNam)
                    .addComponent(jRadioButtonNu)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Tìm kiếm theo: ");

        jComboBoxTimKiemTheo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBoxTimKiemTheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sinh viên", "Tên sinh viên" }));

        jTextFieldTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldTimKiem.setText("Tìm kiếm");
        jTextFieldTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTimKiemMouseClicked(evt);
            }
        });

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-20.png"))); // NOI18N
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel5.setText("CÁC CHỨC NĂNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTimKiemTheo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxTimKiemTheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemMouseClicked
        // TODO add your handling code here:
        jTextFieldTimKiem.setText("");
    }//GEN-LAST:event_jTextFieldTimKiemMouseClicked

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        String regexEmail="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";;
        Pattern pattern = Pattern.compile(regexEmail);
        try {
            if (jTextFieldMaSV.getText().equals("") || jTextFieldTenSV.getText().equals("") || jTextFieldDiaChi.getText().equals("") || jTextFieldEmail.getText().equals("")) {
                throw new Exception("Không được bỏ trống các ô nhập liệu");
            }
            ResultSet rs = sinhvienBLL.getThongTinSinhVien(jTextFieldMaSV.getText());
            if(rs.next()==true)
                throw new Exception("Đã có sinh viên này");
            Matcher matcher = pattern.matcher(jTextFieldEmail.getText());
            if(matcher.find()==false)
                throw new Exception("Email không đúng định dạng");
            String maSV = jTextFieldMaSV.getText();
            String tenSV = jTextFieldTenSV.getText();
            int gioiTinh;
            if (jRadioButtonNam.isSelected()) {
                gioiTinh = 0;
            } else {
                gioiTinh = 1;
            }
            String diaChi = jTextFieldDiaChi.getText();
            String email = jTextFieldEmail.getText();
            sinhvienBLL.insertSinhVien(maSV, tenSV, gioiTinh, diaChi, email);
            LoadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonTimKiem, e.getMessage(), "Lỗi nhập liệu", HEIGHT);
        }

    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:

        try {
            int index = jTableThongTinSV.getSelectedRow();
            if (index < 0) {
                throw new Exception("Vui lòng chọn thành viên cần xóa");
            }
            int rsPane = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rsPane == JOptionPane.YES_OPTION) {
                sinhvienBLL.deleteSinhVien(sinhViens.get(index).getMaSV());
                sinhViens.remove(index);
                LoadBang();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonXoa, e.getMessage(), "Lỗi", HEIGHT);
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldMaSV.getText().equals("") || jTextFieldTenSV.getText().equals("") || jTextFieldDiaChi.getText().equals("") || jTextFieldEmail.getText().equals("")) {
                throw new Exception("Không được bỏ trống các ô nhập liệu");
            }
            String maSV = jTextFieldMaSV.getText();
            String tenSV = jTextFieldTenSV.getText();
            int gioiTinh;
            if (jRadioButtonNam.isSelected()) {
                gioiTinh = 0;
            } else {
                gioiTinh = 1;
            }
            String diaChi = jTextFieldDiaChi.getText();
            String email = jTextFieldEmail.getText();
            int indexTable = jTableThongTinSV.getSelectedRow();
            sinhViens.set(indexTable, new DTOSinhVien(maSV, tenSV, gioiTinh, diaChi, email));
            sinhvienBLL.updateSinhVien(maSV, tenSV, gioiTinh, diaChi, email);
            LoadBang();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonTimKiem, e.getMessage(), "Lỗi nhập liệu", HEIGHT);
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldTimKiem.getText().equals("")) {
                throw new Exception("Vui lòng nhập thông tin tìm kiếm");
            }
            if (jComboBoxTimKiemTheo.getSelectedIndex() == 0) {
                rs = sinhvienBLL.getThongTinSinhVien(jTextFieldTimKiem.getText());
            }
            if (jComboBoxTimKiemTheo.getSelectedIndex() == 1) {
                rs = sinhvienBLL.SearchSinhVienTheoTen(jTextFieldTimKiem.getText());
            }
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(jButtonTimKiem, "Không tìm thấy thông tin", "Không tìm thấy!!", HEIGHT);
            } else {
                sinhViens.clear();
                do {
                    DTOSinhVien a = new DTOSinhVien();
                    a.setMaSV(rs.getString("MaSV"));
                    a.setTenSV(rs.getString("TenSV"));
                    a.setGioiTinh(Integer.parseInt(rs.getString("GioiTinh")));
                    a.setDiaChi(rs.getString("DiaChi"));
                    a.setEmail(rs.getString("Email"));
                    sinhViens.add(a);
                } while (rs.next());
            }
            LoadBang();
        } catch (SQLException ex) {
            Logger.getLogger(PanelQuanLySinhVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jButtonTimKiem, ex.getMessage(), "Lỗi nhập liệu", HEIGHT);
        }
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        LoadData();
        jTextFieldTenSV.setText("");
        jTextFieldMaSV.setText("");
        jTextFieldEmail.setText("");
        jTextFieldDiaChi.setText("");
        jTextFieldTimKiem.setText("Tìm kiếm");
        jRadioButtonNam.setSelected(true);
        jTextFieldMaSV.setEnabled(true);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTableThongTinSVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableThongTinSVMousePressed
        // TODO add your handling code here:
        int index = jTableThongTinSV.getSelectedRow();
        jTextFieldMaSV.setText(sinhViens.get(index).getMaSV());
        jTextFieldTenSV.setText(sinhViens.get(index).getTenSV());
        if (sinhViens.get(index).getGioiTinh() == 0) {
            jRadioButtonNam.setSelected(true);
        } else {
            jRadioButtonNu.setSelected(true);
        }
        jTextFieldDiaChi.setText(sinhViens.get(index).getDiaChi());
        jTextFieldEmail.setText(sinhViens.get(index).getEmail());
        jTextFieldMaSV.setEnabled(false);
    }//GEN-LAST:event_jTableThongTinSVMousePressed

    private void jTextFieldMaSVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMaSVKeyPressed
        // TODO add your handling code here:
        String MaSV = jTextFieldMaSV.getText();
        int length = MaSV.length();
        char c = evt.getKeyChar();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {//Kiểm tra xem số nhập vào có là từ 0-9
            if (length <= 10)//kiểm tra độ dài của khung nhập
            {
                jTextFieldMaSV.setEditable(true);
            } else {
                jTextFieldMaSV.setEditable(false);//Nếu >10 thì k cho nhập
            }
        } else {
            //Cho phép sử dụng phím backspace và delete
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextFieldMaSV.setEditable(true);
            } else {
                jTextFieldMaSV.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextFieldMaSVKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGioiTinh;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxTimKiemTheo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableThongTinSV;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMaSV;
    private javax.swing.JTextField jTextFieldTenSV;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
