
import BLL.BLLTaiKhoan;
import DTO.DTOTaiKhoan;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class PanelQuanLyTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyTaiKhoan
     */
    public static ResultSet rs = null;
    public BLLTaiKhoan taiKhoan = new BLLTaiKhoan();
    String tenDangNhap;
    ArrayList<DTOTaiKhoan> taiKhoans = new ArrayList<DTOTaiKhoan>();

    public PanelQuanLyTaiKhoan() {
        initComponents();
        LoadData();
    }
    
    public PanelQuanLyTaiKhoan(String tenDangNhap) {
        initComponents();
        this.tenDangNhap = tenDangNhap;
        LoadData();
    }

    private void LoadBang() {
        jTableThongTinTK.removeAll();
        String[] tieuDe = {"Tên đăng nhập", "Người dùng", "Loại tài khoản"};
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        for (DTOTaiKhoan taiKhoan : taiKhoans) {
            Vector vt = new Vector();
            vt.add(taiKhoan.getTenDangNhap());
            vt.add(taiKhoan.getTenNguoiDung());
            vt.add(taiKhoan.getLoaiTK());
            model.addRow(vt);
        }
        jTableThongTinTK.setModel(model);
    }

    private void LoadData() {
        try {
            taiKhoans.clear();
            rs = taiKhoan.ShowTaiKhoan();
            jTableThongTinTK.removeAll();
            String[] tieuDe = {"Tên đăng nhập", "Người dùng", "Loại tài khoản"};
            DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
            while (rs.next()) {
                Vector vt = new Vector();
                DTOTaiKhoan taiKhoan = new DTOTaiKhoan();
                taiKhoan.setTenDangNhap(rs.getString("TenDangNhap"));
                taiKhoan.setMatKhau(rs.getString("MatKhau"));
                taiKhoan.setTenNguoiDung(rs.getString("TenNguoiDung"));
                taiKhoan.setLoaiTK(rs.getInt("loaiTaiKhoan"));
                taiKhoans.add(taiKhoan);
            }
            LoadBang();
        } catch (SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(PanelQuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableThongTinTK = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonTaoTK = new javax.swing.JButton();
        jButtonSuaTK = new javax.swing.JButton();
        jButtonXoaTK = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(85, 65, 118));

        jTableThongTinTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableThongTinTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableThongTinTK.setFocusable(false);
        jTableThongTinTK.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableThongTinTK.setRowHeight(25);
        jTableThongTinTK.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTableThongTinTK.setShowVerticalLines(false);
        jTableThongTinTK.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableThongTinTK);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButtonTaoTK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTaoTK.setText("Tạo tài khoản");
        jButtonTaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoTKActionPerformed(evt);
            }
        });

        jButtonSuaTK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonSuaTK.setText("Sửa tài khoản");
        jButtonSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaTKActionPerformed(evt);
            }
        });

        jButtonXoaTK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonXoaTK.setText("Xóa tài khoản");
        jButtonXoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaTKActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextFieldTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldTimKiem.setText("Nhập tên đăng nhập");
        jTextFieldTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTimKiemMouseClicked(evt);
            }
        });

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-20.png"))); // NOI18N
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel1.setText("CÁC CHỨC NĂNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonTaoTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSuaTK, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jButtonXoaTK))
                            .addGap(60, 60, 60))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jButtonTaoTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSuaTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonXoaTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReset)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemMouseClicked
        // TODO add your handling code here:
        jTextFieldTimKiem.setText("");
    }//GEN-LAST:event_jTextFieldTimKiemMouseClicked

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldTimKiem.getText().equals("")) {
                throw new Exception("Vui lòng nhập thông tin tìm kiếm!!");
            }
            rs = taiKhoan.TimKiemTaiKhoan(jTextFieldTimKiem.getText());
            if (rs.next()) {
                taiKhoans.clear();
                Vector vt = new Vector();
                DTOTaiKhoan taiKhoan = new DTOTaiKhoan();
                taiKhoan.setTenDangNhap(rs.getString("TenDangNhap"));
                taiKhoan.setMatKhau(rs.getString("MatKhau"));
                taiKhoan.setTenNguoiDung(rs.getString("TenNguoiDung"));
                taiKhoan.setLoaiTK(rs.getInt("loaiTaiKhoan"));
                taiKhoans.add(taiKhoan);
                LoadBang();
            } else {
                JOptionPane.showMessageDialog(jButtonTimKiem, "Không tìm thấy thông tin", "Không tìm thấy!!", HEIGHT);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelQuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jButtonTimKiem, ex.getMessage(), "Lỗi nhập liệu", HEIGHT);
        }
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonTaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoTKActionPerformed
        // TODO add your handling code here:
        TaoTaiKhoan dangKiTaiKhoan = new TaoTaiKhoan(null, true);
        dangKiTaiKhoan.setVisible(true);
        LoadData();
    }//GEN-LAST:event_jButtonTaoTKActionPerformed

    private void jButtonSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaTKActionPerformed
        // TODO add your handling code here:
        int index = jTableThongTinTK.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(jButtonSuaTK, "Vui lòng chọn tài khoản cần sửa", "Lỗi", HEIGHT);
        } else {
            TaoTaiKhoan dangKiTaiKhoan = new TaoTaiKhoan(null, true, taiKhoans.get(index).getTenDangNhap(), taiKhoans.get(index).getMatKhau(), taiKhoans.get(index).getTenNguoiDung(), taiKhoans.get(index).getLoaiTK());
            dangKiTaiKhoan.setVisible(true);
            LoadData();
        }
    }//GEN-LAST:event_jButtonSuaTKActionPerformed

    private void jButtonXoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaTKActionPerformed
        // TODO add your handling code here
        try {
            int index = jTableThongTinTK.getSelectedRow();
            if (index < 0) {
                throw new Exception("Vui lòng chọn tài khoản cần xóa");
            }
            if(taiKhoans.get(index).getTenDangNhap().equals(tenDangNhap)==true)
                throw new Exception("Không thể xóa tài khoản của chính mình");
            int rsPane = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rsPane == JOptionPane.YES_OPTION) {

                taiKhoan.deleteTaiKhoan(taiKhoans.get(index).getTenDangNhap());
                taiKhoans.remove(index);
                LoadBang();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonXoaTK, e.getMessage(), "Lỗi", HEIGHT);
        }
    }//GEN-LAST:event_jButtonXoaTKActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        LoadData();
        jTextFieldTimKiem.setText("Nhập tên đăng nhập");
    }//GEN-LAST:event_jButtonResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSuaTK;
    private javax.swing.JButton jButtonTaoTK;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoaTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableThongTinTK;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
