
import BLL.BLLDanhMuc;
import BLL.BLLNhaXuatBan;
import DTO.DTONhaXuatBan;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class PaneQuanLylNhaXuatBan extends javax.swing.JPanel {

    /**
     * Creates new form PanelNhaXuatBan
     */
    public static ResultSet rs = null;
    public BLL.BLLNhaXuatBan nhaXuatBan = new BLLNhaXuatBan();
    public ArrayList<DTO.DTONhaXuatBan> nhaXuatBans = new ArrayList<DTONhaXuatBan>();

    public PaneQuanLylNhaXuatBan() {
        initComponents();
        LoadData();
    }

    private void LoadBang() {
        jTableNhaXuatBan.removeAll();
        String[] tieuDe = {"STT", "Tên nhà xuất bản", "Địa chỉ", "Số điện thoại"};
        DefaultTableModel model = new DefaultTableModel(tieuDe, 0);
        int i = 1;
        for (DTONhaXuatBan nhaXuatBan : nhaXuatBans) {
            Vector vt = new Vector();
            vt.add(String.valueOf(i));
            vt.add(nhaXuatBan.getTenNXB());
            vt.add(nhaXuatBan.getDiaChi());
            vt.add(nhaXuatBan.getSoDT());
            model.addRow(vt);
            i++;
        }
        jTableNhaXuatBan.setModel(model);
    }

    private void LoadData() {
        try {
            nhaXuatBans.clear();
            rs = nhaXuatBan.ShowNhaXuatBan();
            while (rs.next()) {
                DTONhaXuatBan a = new DTONhaXuatBan();
                a.setMaNXB(Integer.parseInt(rs.getString("MaNXB")));
                a.setTenNXB(rs.getString("TenNXB"));
                a.setDiaChi(rs.getString("DiaChi"));
                a.setSoDT(rs.getString("SoDT"));
                nhaXuatBans.add(a);
            }
            LoadBang();
        } catch (SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(PanelQuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhaXuatBan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTenNXB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSoDT = new javax.swing.JTextField();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(85, 65, 118));
        setForeground(new java.awt.Color(240, 240, 240));

        jTableNhaXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNhaXuatBan.setFocusable(false);
        jTableNhaXuatBan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableNhaXuatBan.setRowHeight(25);
        jTableNhaXuatBan.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTableNhaXuatBan.setShowVerticalLines(false);
        jTableNhaXuatBan.getTableHeader().setReorderingAllowed(false);
        jTableNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhaXuatBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhaXuatBan);

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên nhà xuất bản:");

        jTextFieldTenNXB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Địa chỉ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số điện thoại:");

        jTextFieldSoDT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldSoDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoDTActionPerformed(evt);
            }
        });
        jTextFieldSoDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSoDTKeyPressed(evt);
            }
        });

        jTextFieldDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSoDT)
                    .addComponent(jTextFieldTenNXB)
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldTimKiem.setText("Nhập tên nhà xuất bản");

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-20.png"))); // NOI18N
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jLabel4.setText("CÁC CHỨC NĂNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa)
                    .addComponent(jButtonClear))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        String tenNXB = jTextFieldTenNXB.getText();
        String diaChi = jTextFieldDiaChi.getText();
        String SoDT = jTextFieldSoDT.getText();
        nhaXuatBan.insertNhaXuatBan(tenNXB, diaChi, SoDT);
        System.out.println(tenNXB +", " +diaChi +", "+ SoDT);
        LoadData();
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jTableNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhaXuatBanMouseClicked
        // TODO add your handling code here:
        int index = jTableNhaXuatBan.getSelectedRow();
        jTextFieldTenNXB.setText(jTableNhaXuatBan.getModel().getValueAt(index, 1).toString());
        jTextFieldDiaChi.setText(jTableNhaXuatBan.getModel().getValueAt(index, 2).toString());
        jTextFieldSoDT.setText(jTableNhaXuatBan.getModel().getValueAt(index, 3).toString());
    }//GEN-LAST:event_jTableNhaXuatBanMouseClicked

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        try {
            int index = jTableNhaXuatBan.getSelectedRow();
            if (index < 0) {
                throw new Exception("Vui lòng chọn nhà xuất bản cần xóa!!");
            }
            int rsPane = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (rsPane == JOptionPane.YES_OPTION) {

                int maNXB_xoa = nhaXuatBans.get(index).getMaNXB();
                nhaXuatBan.deleteNhaXuatBan(maNXB_xoa);
                nhaXuatBans.remove(index);
                LoadBang();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonXoa, e.getMessage(), "Lỗi", HEIGHT);
        }
        //nhaXuatBan.deleteNhaXuatBan(jTableNhaXuatBan)
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            nhaXuatBans.clear();
            rs = nhaXuatBan.SearchNhaXuatBan(jTextFieldTimKiem.getText());
            while (rs.next()) {
                DTONhaXuatBan a = new DTONhaXuatBan();
                a.setMaNXB(Integer.parseInt(rs.getString("MaNXB")));
                a.setTenNXB(rs.getString("TenNXB"));
                a.setDiaChi(rs.getString("DiaChi"));
                a.setSoDT(rs.getString("SoDT"));
                nhaXuatBans.add(a);
            }
            LoadBang();
        } catch (SQLException e) {
        } catch (Exception ex) {
            Logger.getLogger(PanelQuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldTenNXB.setText("");
        jTextFieldDiaChi.setText("");
        jTextFieldSoDT.setText("");
        jTextFieldTimKiem.setText("Nhập tên nhà xuất bản");
        LoadData();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        int index = jTableNhaXuatBan.getSelectedRow();
        nhaXuatBan.updateNhaXuatBan(nhaXuatBans.get(index).getMaNXB(), jTextFieldTenNXB.getText(), jTextFieldDiaChi.getText(), jTextFieldSoDT.getText());
        LoadData();
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jTextFieldSoDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSoDTKeyPressed
        // TODO add your handling code here:
        String soDT = jTextFieldSoDT.getText();
        int length = soDT.length();
        char c = evt.getKeyChar();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {//Kiểm tra xem số nhập vào có là từ 0-9
            if (length < 11)//kiểm tra độ dài của khung nhập
            {
                jTextFieldSoDT.setEditable(true);
            } else {
                jTextFieldSoDT.setEditable(false);//Nếu >10 thì k cho nhập
            }
        } else {
            //Cho phép sử dụng phím backspace và delete
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                jTextFieldSoDT.setEditable(true);
            } else {
                jTextFieldSoDT.setEditable(false);
            }
        }
    }//GEN-LAST:event_jTextFieldSoDTKeyPressed

    private void jTextFieldSoDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoDTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhaXuatBan;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldSoDT;
    private javax.swing.JTextField jTextFieldTenNXB;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
