
import BLL.BLLTaiKhoan;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LongTienSinh
 */
public class TaoTaiKhoan extends javax.swing.JDialog {

    /**
     * Creates new form DangKiTaiKhoan2
     */
    String tenDangNhap;
    BLL.BLLTaiKhoan taiKhoanBLL = new BLLTaiKhoan();

    public TaoTaiKhoan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        jButtonDangKi.setText("Đăng kí");
        jRadioButtonNhanVien.setSelected(true);
    }

    public TaoTaiKhoan(java.awt.Frame parent, boolean modal, String tenDangNhap, String matKhau, String tenNguoiDung, int loai) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.tenDangNhap = tenDangNhap;
        jTextFieldTenDangNhap.setText(tenDangNhap);
        jTextFieldTenDangNhap.setEnabled(false);
        jPasswordFieldMatKhau.setText(matKhau);
        jPasswordFieldMatKhau.setEnabled(false);
        jPasswordFieldXacNhanMatKhau.setText(matKhau);
        jPasswordFieldXacNhanMatKhau.setEnabled(false);
        jTextFieldTenNguoiDung.setText(tenNguoiDung);
        if (loai == 1) {
            jRadioButtonNguoiQuanTri.setSelected(true);
            jRadioButtonNhanVien.setEnabled(false);
        } else {
            jRadioButtonNhanVien.setSelected(true);
        }
        jButtonDangKi.setText("Sửa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLoai = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTenNguoiDung = new javax.swing.JTextField();
        jTextFieldTenDangNhap = new javax.swing.JTextField();
        jRadioButtonNhanVien = new javax.swing.JRadioButton();
        jRadioButtonNguoiQuanTri = new javax.swing.JRadioButton();
        jButtonDangKi = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldMatKhau = new javax.swing.JPasswordField();
        jPasswordFieldXacNhanMatKhau = new javax.swing.JPasswordField();
        jCheckBoxHienThiMatKhau = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên người dùng:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 165, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên đăng nhập:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 27, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 73, -1, -1));

        jTextFieldTenNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.add(jTextFieldTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 162, 253, -1));

        jTextFieldTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.add(jTextFieldTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 24, 254, -1));

        buttonGroupLoai.add(jRadioButtonNhanVien);
        jRadioButtonNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNhanVien.setText("Nhân viên");
        jPanel2.add(jRadioButtonNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 208, -1, -1));

        buttonGroupLoai.add(jRadioButtonNguoiQuanTri);
        jRadioButtonNguoiQuanTri.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonNguoiQuanTri.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNguoiQuanTri.setText("Người quản trị");
        jPanel2.add(jRadioButtonNguoiQuanTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 208, -1, -1));

        jButtonDangKi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonDangKi.setText("Đăng kí");
        jButtonDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangKiActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 306, -1, -1));

        jButtonHuy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 306, 85, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Xác nhận mật khẩu:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 119, -1, -1));

        jPasswordFieldMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.add(jPasswordFieldMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 70, 254, -1));

        jPasswordFieldXacNhanMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.add(jPasswordFieldXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 116, 254, -1));

        jCheckBoxHienThiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBoxHienThiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxHienThiMatKhau.setText("Hiển thị mật khẩu");
        jCheckBoxHienThiMatKhau.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxHienThiMatKhauStateChanged(evt);
            }
        });
        jPanel2.add(jCheckBoxHienThiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 257, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loại tài khoản:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 212, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangKiActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldTenDangNhap.getText().equals("") || String.valueOf(jPasswordFieldMatKhau.getPassword()).equals("") || String.valueOf(jPasswordFieldXacNhanMatKhau.getPassword()).equals("") || jTextFieldTenNguoiDung.getText().equals("")) {
                throw new Exception("Không được để trống các trường nhập");
            }
            int loai;
            if (jRadioButtonNguoiQuanTri.isSelected()) {
                loai = 1;
            } else {
                loai = 0;
            }
            if (String.valueOf(jPasswordFieldMatKhau.getPassword()).equals(String.valueOf(jPasswordFieldXacNhanMatKhau.getPassword()))) {
                if (jButtonDangKi.getText().equals("Đăng kí")) {
                    taiKhoanBLL.insertTaiKhoan(jTextFieldTenDangNhap.getText(), String.valueOf(jPasswordFieldMatKhau.getPassword()), jTextFieldTenNguoiDung.getText(), loai);
                } else {
                    taiKhoanBLL.updateTaiKhoan(jTextFieldTenDangNhap.getText(), String.valueOf(jPasswordFieldMatKhau.getPassword()), jTextFieldTenNguoiDung.getText(), loai);
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(jButtonDangKi, "Xác nhận mật khẩu không đúng", "Lỗi nhập liệu", HEIGHT);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jButtonDangKi, e.getMessage(), "Lỗi nhập liệu", HEIGHT);
        }


    }//GEN-LAST:event_jButtonDangKiActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed


    
    private void jCheckBoxHienThiMatKhauStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxHienThiMatKhauStateChanged
        // TODO add your handling code here:
        if (jCheckBoxHienThiMatKhau.isSelected()) {
            jPasswordFieldMatKhau.setEchoChar((char) 0);
            jPasswordFieldXacNhanMatKhau.setEchoChar((char) 0);
        } else {
            jPasswordFieldMatKhau.setEchoChar('*');
            jPasswordFieldXacNhanMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxHienThiMatKhauStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaoTaiKhoan dialog = new TaoTaiKhoan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLoai;
    private javax.swing.JButton jButtonDangKi;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JCheckBox jCheckBoxHienThiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldMatKhau;
    private javax.swing.JPasswordField jPasswordFieldXacNhanMatKhau;
    private javax.swing.JRadioButton jRadioButtonNguoiQuanTri;
    private javax.swing.JRadioButton jRadioButtonNhanVien;
    private javax.swing.JTextField jTextFieldTenDangNhap;
    private javax.swing.JTextField jTextFieldTenNguoiDung;
    // End of variables declaration//GEN-END:variables
}
